Quiz engine UI changes
avantifellows/quiz-frontend pull request #112
Opened 2023-06-01 11:37 UTC by aryajain14

Fixes #{issue id}

## Summary

- Added scrolling feature on the splash screen
- In the question header,
   - Question Index and Type is aligned to the left side
   - Subject name and section are aligned to the right side
- Added a panel which shows Test name and Id on the left and right respectively.
- Testing was done for the above newly added features (5 tests each on vue-test-utils and cypress)

## Test Plan

- [ ] Test Responsiveness
  - [ ] Laptop (1200px)
  - [ ] Tablet (760px)
  - [ ] Phone (320px)
- [ ] Cross-Browser Testing
  - [ ] Chrome
  - [ ] Firefox
- [ ] ~Local Language Support~
- [ ] Hygiene and Housekeeping
  - [ ] Self-review
  - [ ] Comments have been added appropriately
  - [ ] Check for bundle size [here](https://bundlephobia.com/) if adding a package
  - [ ] Added relevant details like Labels/Projects/Milestones etc.
  - [ ] If adding or removing any environment variable, update `docs/ENV.md`, `.env.example` and the Github workflows.
- [ ] Testing
  - [ ] Wrote tests
  - [ ] Tested locally
  - [ ] Tested on staging
  - [ ] Tested on an actual physical phone
  - [ ] Tested on production
- [ ] Lighthouse Checks
  - [ ] Images have `alt` attributes
  - [ ] Any `<img>` tags have `width` and `height` specified
  - [ ] Any `target="_blank"` links have `rel="noopener"`
  - [ ] Only SVGs are used as images. If PNGs are used, their size has been optimised.
  - [ ] Any SVG buttons without text have their `aria-label` attributes set

2023-06-01 13:04 UTC, deepansh96 requested changes

2023-06-01 13:04 UTC, deepansh96 commented on src/components/Questions/QuestionModal.vue
> +          <div class="row-span-1 text-left h-10 mx-4 py-3 text-xl text-base sm:text-xs md:text-base lg:text-lg xl:text-xl 2xl:text-2xl" style = "@media (max-width: 870px){font-size: 0.75rem; line-hei
why are there tailwind classes along with an inline style attribute? 
`style = "@media (max-width: 870px){font-size: 0.75rem; line-height: 1rem;}">`
You can rewrite this thing using tailwind itself. You can extend the tailwind config and put a custom breakpoint. Take a look at the `tailwind.config.js` file in this project and see how we've added custom breakpoints. Similarly you can add the 870px waala breakpoint and then set the font size and line height

2023-06-01 13:04 UTC, deepansh96 commented on src/components/Splash.vue
> +  <!-- <div class="flex flex-col justify-center h-full" @wheel="preventScrolling"> -->
comment

2023-06-01 13:04 UTC, deepansh96 commented on src/components/Splash.vue
> +  scrollContent(event) {
what does this method do? can you add a comment above this method explaining this?

2023-06-01 13:04 UTC, deepansh96 commented on src/views/Player.vue
> +        :title="title"
this doesn't seem like it is covered in tests, can you check?

2023-06-06 05:45 UTC, sudheshna-donthineni commented on src/components/Scorecard.vue
> +        "flex justify-center bg-[#10B981] hover:bg-green-600 bp-500:w-40 px-6 py-3 bp-500:p-4 bp-500:px-10 sm:p-6 rounded-2xl md:rounded-xl shadow-xl disabled:opacity-50 disabled:pointer-events-none"
why don't you add this colors to the theme?

2023-06-06 05:46 UTC, sudheshna-donthineni commented on tests/e2e/specs/renders-omr-assessment.js
> +  // describe("Resume Session", () => {
why not delete the commented code?

2023-06-12 13:49 UTC, suryabulusu commented on src/components/Questions/Body.vue
> +            class="px-2 w-full mb-20"
remove this

2023-06-12 13:52 UTC, suryabulusu commented on src/components/Questions/Palette/QuestionPalette.vue
> +            class="hover:cursor-pointer mb-12"
u can remove this -- check once

2023-06-15 11:21 UTC, suryabulusu approved these changes
looks good to me! good job!

2023-06-15 11:23 UTC, merged